### ISSUE TITLE
How to create a Disqus account? 

### ISSUE THREAD

**Issue by pirreke** [bubobox/help#7]
Navigate to https://disqus.com/profile/signup/ and create an account. Fill in your personal details. The company account name can be filled in later.   

![screenshot 2016-11-04 12 48 01](https://cloud.githubusercontent.com/assets/8588208/20669497/cc629024-b574-11e6-8479-3767fb6de204.png)

Next, you have two options you can chose from. Since others need to be able to comment in our community, you select "I want to install Disqus on my site". 

![screenshot 2016-11-04 12 50 53](https://cloud.githubusercontent.com/assets/8588208/20669526/032bf0c8-b575-11e6-87cc-265ee3b7999d.png)

Next, we need to set up Disqus to use it in Ambassify. On top of the screen, you fill in the name of your company. Underneath, you fill in your unique Disqus URL. 
It's this unique URL you need to fill in the Ambassify settings later on. 

**_Attention: Once you've chosen a unique name, you can't change it anymore._**
_Tip: Keep this unique Disqus URL simple and short, but make sure users recognise it's your company that manages the account._ 

![screenshot 2016-11-04 12 52 17](https://cloud.githubusercontent.com/assets/8588208/20669572/3c0f43d6-b575-11e6-8c10-c06b8c9b85f2.png)

You are ready to use Disqus in Ambassify. [Click here to configure your Disqus account in Ambassify](https://my.ambassify.com/#/community/configure). 

Forgotten your unique Disqus URL? Log in to your Disqus account, click on "Settings" on top of the screen and select "General" in the menu on the left. Next to _Shortname_, you can find your unique Disqus URL.

![screenshot 2016-11-04 12 55 33](https://cloud.githubusercontent.com/assets/8588208/20669783/4612d388-b576-11e6-9abb-6d54e2d36d74.png)

Happy commenting.

**Comment by Gertt** [comment]
Integrated
